export type UserRole = 'Administrateur' | 'Juge' | 'Greffier' | 'Secrétaire' | 'Président';

export interface UserPermissions {
  canCreateCases: boolean;
  canDeleteCases: boolean;
  canEditPlumitif: boolean;
  canManageHearings: boolean;
  canUploadDocuments: boolean;
  canVerifyIntegrity: boolean;
}

export interface User {
  id: string;
  username: string;
  fullName: string;
  role: UserRole;
  tribunal: string;
  avatar?: string;
  mfaEnabled: boolean;
  biometricRegistered: boolean;
  active?: boolean;
  permissions?: UserPermissions;
}

export interface CourtProfile {
  id: string;
  name: string;
  type: string; // e.g., 'Tribunal de Grande Instance', 'Tribunal de Première Instance', 'Cour d'Appel', 'Cour Suprême'
  president: string;
  address: string;
  phone: string;
  email: string;
  jurisdictionRegion: string; // e.g., 'Centre', 'Littoral', etc.
  foundingDate: string;
  activeChambers: string[];
}

export interface CaseDocument {
  id: string;
  name: string;
  date: string;
  type: string; // e.g., 'Requête', 'Mémoire', 'Procès-verbal', 'Pièce jointe'
  hash: string; // Cryptographic SHA-256 simulation
  size: string;
  uploadedBy: string;
  secure: boolean;
  hearingId?: string; // Link to specific hearing if provided at one
}

export interface Case {
  id: string;
  numDossier: string; // Cameroonian style, e.g., "TGI-YDE/012-P/2026"
  title: string;
  description: string;
  tribunal: string; // e.g., "TGI du Mfoundi (Yaoundé)", "TPI de Douala-Bonanjo"
  nature: 'Pénal' | 'Civil' | 'Administratif' | 'Commercial' | 'Social';
  status: 'En cours' | 'Mis en délibéré' | 'Clôturé' | 'Archivé';
  dateCreation: string;
  parties: string; // e.g., "Ministère Public & X vs Y"
  priority: 'Basse' | 'Moyenne' | 'Haute' | 'Urgente';
  magistratId: string;
  magistratName: string;
  documents: CaseDocument[];
  notesDeliberation?: string; // Judge-only notes
}

export interface Hearing {
  id: string;
  caseId: string;
  numDossier: string;
  caseTitle: string;
  date: string; // YYYY-MM-DD
  time: string; // HH:MM
  room: string; // e.g., "Chambre Civile I", "Salle d'Audience A"
  status: 'Planifiée' | 'En cours' | 'Terminée' | 'Reportée';
  notes: string; // Draft notes to compile
  compteRendu?: string; // Generated by Gemini
  greffierName: string;
  reporter?: string;
}

export interface ActivityLog {
  id: string;
  userId: string;
  userName: string;
  userRole: UserRole;
  action: string;
  timestamp: string;
  ip: string;
  details: string;
  integrityHash: string; // Block-chain style audit integrity log
}

export interface AppStats {
  totalCases: number;
  activeHearings: number;
  urgentCases: number;
  digitizedDocsCount: number;
  byNature: { name: string; value: number }[];
  byStatus: { name: string; value: number }[];
  monthlyActivity: { month: string; dossiers: number; audiences: number }[];
}
